version: '3'
# TODO: change all the default ports to improve security
services:
  db:
    image: postgres:12.2-alpine # TODO: check alpine version fro small image size
    ports: 
      - 5432:5432
    env_file:
      - config/db/db_env
    networks: 
      - db_network
    volumes:
      - ./data/db:/var/lib/postgresql/data
  
  # TODO: name of the project will be used in the command line
  djangoapp:
    build: .
    volumes:
    # TODO: volume mounting for syncing local repo to container
      - ./app/:/src
      - ./static/:/static
      - ./media/:/media
    networks:  # <-- here
      - nginx_network
      - db_network
    depends_on: 
      - db

  # TODO: small image size. check alphine
  nginx:
    image: nginx:1.17.10-alpine
    ports:
      - 8000:80
    volumes:
    # TODO: nginx mapping to loca folder
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static/:/static
      - ./media:/media
    depends_on:
      - djangoapp
    networks:  # <-- maps to the network bridge setting
      - nginx_network


networks:  # <-- and here
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

